QLSV/Controllers/HomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLSV.Models;
namespace QLSV.Controllers
{
    public class HomesController : Controller
    {
        private Model1 db = new Model1();
        // GET: Homes
        public ActionResult Index()
        {
            var khoa = db.Khoas.Count();
            ViewBag.sokhoa = khoa;
            var nganh = db.Nganhs.Count();
            ViewBag.songanh = nganh;
            var monhoc = db.MonHocs.Count();
            ViewBag.somonhoc = monhoc;
            var giangvien = db.GiangViens.Count();
            ViewBag.sogiangvien = giangvien;
            var lop = db.Lops.Count();
            ViewBag.solop = lop;
            var sinhvien = db.SinhViens.Count();
            ViewBag.sosinhvien = sinhvien;
            return View();
        }
        public ActionResult GetKhoa()
        {
            int cntt = db.Nganhs.Where(x => x.MaKhoa == "KHOA01").Count();
            int sp = db.Nganhs.Where(x => x.MaKhoa == "KHOA02").Count();
            int toanthongke = db.Nganhs.Where(x => x.MaKhoa == "KHOA03").Count();
            int qtkd = db.Nganhs.Where(x => x.MaKhoa == "KHOA04").Count();
            int khtn = db.Nganhs.Where(x => x.MaKhoa == "KHOA05").Count();
            int khxh = db.Nganhs.Where(x => x.MaKhoa == "KHOA06").Count();
            int lyluanchinhtri = db.Nganhs.Where(x => x.MaKhoa == "KHOA07").Count();
            int gdtc = db.Nganhs.Where(x => x.MaKhoa == "KHOA08").Count();

            DemKhoa dem = new DemKhoa();
            dem.cntt = cntt;
            dem.sp = sp;
            dem.gdtc = gdtc;
            dem.khtn = khtn;
            dem.khxh = khxh;
            dem.lyluanchinhtri = lyluanchinhtri;
            dem.qtkd = qtkd;
            dem.toanthongke = toanthongke;
            return Json(dem, JsonRequestBehavior.AllowGet);

        }
        public ActionResult GetDiem()
        {
            int diema = db.Diems.Where(x => x.DiemChu == "A").Count();
            int diemb = db.Diems.Where(x => x.DiemChu == "B").Count();
            int diemc = db.Diems.Where(x => x.DiemChu == "C").Count();
            int diemd = db.Diems.Where(x => x.DiemChu == "D").Count();
            int dieme = db.Diems.Where(x => x.DiemChu == "E").Count();
            int diemf = db.Diems.Where(x => x.DiemChu == "F").Count();
            int diemacong = db.Diems.Where(x => x.DiemChu == "A+").Count();
            int diembcong = db.Diems.Where(x => x.DiemChu == "B+").Count();

            DemDiem dem = new DemDiem();
            dem.a = diema;
            dem.b = diemb;
            dem.c = diemc;
            dem.d = diemd;
            dem.e = dieme;
            dem.f = diemf;
            dem.acong = diemacong;
            dem.bcong = diembcong;
            return Json(dem, JsonRequestBehavior.AllowGet);

        }
        public class DemKhoa
        {
            public int cntt { get; set; }
            public int sp { get; set; }
            public int gdtc { get; set; }
            public int khtn { get; set; }
            public int khxh { get; set; }
            public int lyluanchinhtri { get; set; }
            public int qtkd { get; set; }
            public int toanthongke { get; set; }

        }
        public class DemDiem
        {
            public int a { get; set; }
            public int b { get; set; }
            public int c { get; set; }
            public int d { get; set; }
            public int e { get; set; }
            public int f { get; set; }
            public int acong { get; set; }
            public int bcong { get; set; }

        }
    }
}

QLSV/Views/Shared/GV_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: Cambria;
        }


        .navbar {
            padding: 0;
            display: flex;
            justify-content: space-between;
        }

        .cha {
            align-items: center;
            background-color: #37497E;
            font-size: 20px;
            z-index: 999;
            width: 100%;
            position: fixed;
            top: 0;
            left: 0;
        }

        .nav-list {
            list-style: none;
            display: flex;
            padding-left: 0;
            margin: auto 16px;
            height: 100%;
        }

        .menu-items {
            margin: 0 8px;
            color: #fff;
        }

        .menu-dangnhap {
            display: flex;
            align-items: center;
            margin: auto 16px;
        }

        .navbar {
            padding: 10px 0px;
        }

        .nav-list .menu-items .thea {
            font-weight: bold;
            cursor: pointer;
            position: relative;
            transition: 0.3s ease;
            text-decoration: none;
            color: #fff;
            padding: inherit;
            box-sizing: border-box;
            padding: 34px 20px;
        }

        .thea:hover {
            background-color: #0000FF;
            border-radius: 5px;
        }

        .nav-list1 {
            position: absolute;
            right: 0;
            background-color: #37497E;
            font-size: 14px;
            z-index: 1000;
            list-style: none;
            outline: none;
            padding: 20px;
            width: 300px;
            align-items: center;
            transition: 2s ease;
            display: none;
            position: absolute;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: auto;
        }


        .thea1 {
            cursor: pointer;
            position: relative;
            color: white;
            text-decoration: none;
            font-size: 20px;
            transition: 0.2s ease;
            font-weight: bold;
        }

        .menu-items1 {
            float: none;
            text-align: center;
            display: block;
        }

        .thea1:hover {
            border-radius: 2px;
            Tính Nguyễn width:100%;
            height: 100%;
            color: #fff;
            background-color: #0000FF;
            padding: 17px 15px;
        }

        .menu-items:hover .nav-list1 {
            background-color: #37497E;
            display: block;
        }

        .bentrai {
            flex: 2;
        }

        img {
            background-size: 100%;
        }

        .main-1 {
            background-color: #37497E;
            color: #fff;
        }

        .row {
            display: flex;
            align-items: center;
        }

        .ndf-main1 span {
            list-style: none;
            opacity: 0.8;
            color: #fff
        }

        footer {
            margin-top: 100px;
        }

        .ndft {
            list-style: none;
            margin: 0;
            padding: 0;
            opacity: 0.8;
        }

            .ndft a {
                text-decoration: none;
            }

        .body-content {
            margin-top: 100px;
        }

        .text-danger {
            font-size: 20px;
        }

        .chinh {
            display: flex;
            justify-content: space-around;
        }

        .cangiua {
            display: block;
        }

        .anh-2 {
            display: flex;
            align-content: center;
        }

        .benphai {
            align-items: center;
        }

        .rounded-circle {
            width: 30px;
            height: 30px;
            background: #7fee1d;
            -moz-border-radius: 60px;
            -webkit-border-radius: 60px;
            border-radius: 60px;
        }
    </style>
</head>
<body>
    <div class="cha">
        <nav class=" navbar navbar-expand-lg navbar-light ">

            <img src="https://qnu.edu.vn/Resources/Images/0logoDHQNnew.jpg" style="height: 70px; width: 70px; padding:0;">
            <ul class="nav-list bentrai">
                <li class="menu-items active"><a class="thea" href="@Url.Action("Index", "Homes")">Trang chủ</a></li>
                <li class="menu-items active"><a class="thea" href="@Url.Action("gv_Khoa_Index", "Khoas")">Khoa</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("gv_Nganh_Index", "Nganhs")">Ngành</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("gv_MonHoc_Index", "MonHocs")">Môn học</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("gv_Diem_Index", "Diems")">Điểm</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("gv_SinhVien_Index", "SinhViens")">Sinh viên</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("gv_Lop_Index", "Lops")">Lớp</a></li>
            </ul>

            <ul class="nav-list benphai d-flex">
                <li class="menu-items">
                    <a></a><img class="rounded-circle" src="~/Content/IMG/@Session["HinhAnh"]" />
                    <ul class="nav-list1">
                        <li class="menu-items1">
                            <a href="@Url.Action("GiangVien","ThongTin")" class="thea1">Thông tin tài khoản</a>
                        </li>
                        <hr>
                        <li class="menu-items1">
                            <a class="thea1" href="@Url.Action("Thoat","DangNhaps")">Đăng xuất</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

    </div>
    <div class="body-content">
        @RenderBody()
    </div>
    <footer>
        <section class="main main-1">
            <div class="container">
                <div class="chinh d-flex">
                    <div class="anh-2 mt-5">
                        <img src="https://qnu.edu.vn/Resources/Images/0logoDHQNnew.jpg" style="height:170px; width:170px;">
                    </div>
                    <div class="cangiua mt-4">
                        <div>
                            <hr style="width:200px; color:#ff0000; opacity:1; height:2px;">
                            <p class="text-uppercase thep"><b>Thông tin liên hệ</b></p>
                            <ul class="ndft">
                                <li class="d-flex">
                                    <p><i class="bi bi-geo-alt-fill"></i></p>
                                    <p class="fa fa-home"></p>
                                    <span style="margin-left:10px">107 An Dương Vương</span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-envelope"></i></p>
                                    <span style="margin-left:10px">
                                        dqn@moet.edu.vn - tuvantuyensinh@qnu.edu.vn -
                                        dhqn@qnu.edu.vn
                                    </span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-telephone-fill"></i></p>
                                    <span style="margin-left:10px">(84-256) 3846156; Fax: (84-256) 3846089</span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-globe"></i></p>
                                    <a style="color: white; margin-left:10px " href="www.qnu.edu.vn"> www.qnu.edu.vn</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="mt-4">
                        <hr style="width:100px; color:#ff0000; opacity:1; height:2px;">
                        <p class="text-uppercase"><b>link liên kết</b></p>
                        <div class="module  useful-link ">
                            <ul class="ndft">
                                <li>
                                    <p class="fa fa-home"></p>
                                    <a href="https://www.qnu.edu.vn/#" style="color:#fff">Bộ giáo dục và đào tạo</a>
                                </li>
                                <li>
                                    <p class="fa fa-home"></p>
                                    <a href="https://www.qnu.edu.vn/#" style="color:#fff">
                                        Tạp chí giáo dục
                                    </a>
                                </li>


                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.menu-items').on("click", function () {
                $(this).siblings().removeClass('active');
                $(this).addClass('active');
            });
        });
    </script>
</body>
</html>

QLSV/Views/Shared/SV_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: Cambria;
        }


        .navbar {
            padding: 0;
            display: flex;
            justify-content: space-between;
        }

        .cha {
            align-items: center;
            background-color: #37497E;
            font-size: 20px;
            z-index: 999;
            width: 100%;
            position: fixed;
            top: 0;
            left: 0;
        }

        .nav-list {
            list-style: none;
            display: flex;
            padding-left: 0;
            margin: auto 16px;
            height: 100%;
        }

        .menu-items {
            margin: 0 8px;
            color: #fff;
        }

        .menu-dangnhap {
            display: flex;
            align-items: center;
            margin: auto 16px;
        }

        .navbar {
            padding: 10px 0px;
        }

        .nav-list .menu-items .thea {
            font-weight: bold;
            cursor: pointer;
            position: relative;
            transition: 0.3s ease;
            text-decoration: none;
            color: #fff;
            padding: inherit;
            box-sizing: border-box;
            padding: 34px 20px;
        }

        .thea:hover {
            background-color: #0000FF;
            border-radius: 5px;
        }

        .nav-list1 {
            position: absolute;
            right: 0;
            background-color: #37497E;
            font-size: 14px;
            z-index: 1000;
            list-style: none;
            outline: none;
            padding: 20px;
            width: 300px;
            align-items: center;
            transition: 2s ease;
            display: none;
            position: absolute;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: auto;
        }


        .thea1 {
            cursor: pointer;
            position: relative;
            color: white;
            text-decoration: none;
            font-size: 20px;
            transition: 0.2s ease;
            font-weight: bold;
        }

        .menu-items1 {
            float: none;
            text-align: center;
            display: block;
        }

        .thea1:hover {
            border-radius: 2px;
            Tính Nguyễn width:100%;
            height: 100%;
            color: #fff;
            background-color: #0000FF;
            padding: 17px 15px;
        }

        .menu-items:hover .nav-list1 {
            background-color: #37497E;
            display: block;
        }

        .bentrai {
            flex: 2;
        }

        img {
            background-size: 100%;
        }

        .main-1 {
            background-color: #37497E;
            color: #fff;
        }

        .row {
            display: flex;
            align-items: center;
        }

        .ndf-main1 span {
            list-style: none;
            opacity: 0.8;
            color: #fff
        }

        footer {
            margin-top: 100px;
        }

        .ndft {
            list-style: none;
            margin: 0;
            padding: 0;
            opacity: 0.8;
        }

            .ndft a {
                text-decoration: none;
            }

        .body-content {
            margin-top: 100px;
        }

        .text-danger {
            font-size: 20px;
        }

        .chinh {
            display: flex;
            justify-content: space-around;
        }

        .cangiua {
            display: block;
        }

        .anh-2 {
            display: flex;
            align-content: center;
        }

        .benphai {
            align-items: center;
        }

        .rounded-circle {
            width: 30px;
            height: 30px;
            background: #7fee1d;
            -moz-border-radius: 60px;
            -webkit-border-radius: 60px;
            border-radius: 60px;
        }
    </style>
</head>
<body>
    <div class="cha">
        <nav class=" navbar navbar-expand-lg navbar-light ">

            <img src="https://qnu.edu.vn/Resources/Images/0logoDHQNnew.jpg" style="height: 70px; width: 70px; padding:0;">
            <ul class="nav-list bentrai">
                <li class="menu-items active"><a class="thea" href="@Url.Action("Index", "Homes")">Trang chủ</a></li>
                <li class="menu-items active"><a class="thea" href="@Url.Action("sv_Khoa_Index", "Khoas")">Khoa</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("sv_Nganh_Index", "Nganhs")">Ngành</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("sv_MonHoc_Index", "MonHocs")">Môn học</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("sv_Diem_Index", "Diems")">Điểm</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("sv_GiangVien_Index", "GiangViens")">Giảng viên</a></li>
                <li class="menu-items "> <a class="thea" href="@Url.Action("sv_Lop_Index", "Lops")">Lớp</a></li>
            </ul>

            <ul class="nav-list benphai d-flex">
                <li class="menu-items">
                    <a></a><img class="rounded-circle" src="~/Content/IMG/@Session["HinhAnh"]" />
                    <ul class="nav-list1">
                        <li class="menu-items1">
                            <a href="@Url.Action("SinhVien","ThongTin")" class="thea1">Thông tin tài khoản</a>
                        </li>
                        <hr>
                        <li class="menu-items1">
                            <a class="thea1" href="@Url.Action("Thoat","DangNhaps")">Đăng xuất</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

    </div>
    <div class="body-content">
        @RenderBody()
    </div>
    <footer>
        <section class="main main-1">
            <div class="container">
                <div class="chinh d-flex">
                    <div class="anh-2 mt-5">
                        <img src="https://qnu.edu.vn/Resources/Images/0logoDHQNnew.jpg" style="height:170px; width:170px;">
                    </div>
                    <div class="cangiua mt-4">
                        <div>
                            <hr style="width:200px; color:#ff0000; opacity:1; height:2px;">
                            <p class="text-uppercase thep"><b>Thông tin liên hệ</b></p>
                            <ul class="ndft">
                                <li class="d-flex">
                                    <p><i class="bi bi-geo-alt-fill"></i></p>
                                    <p class="fa fa-home"></p>
                                    <span style="margin-left:10px">107 An Dương Vương</span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-envelope"></i></p>
                                    <span style="margin-left:10px">
                                        dqn@moet.edu.vn - tuvantuyensinh@qnu.edu.vn -
                                        dhqn@qnu.edu.vn
                                    </span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-telephone-fill"></i></p>
                                    <span style="margin-left:10px">(84-256) 3846156; Fax: (84-256) 3846089</span>
                                </li>
                                <li class="d-flex">
                                    <p><i class="bi bi-globe"></i></p>
                                    <a style="color: white; margin-left:10px " href="www.qnu.edu.vn"> www.qnu.edu.vn</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="mt-4">
                        <hr style="width:100px; color:#ff0000; opacity:1; height:2px;">
                        <p class="text-uppercase"><b>link liên kết</b></p>
                        <div class="module  useful-link ">
                            <ul class="ndft">
                                <li>
                                    <p class="fa fa-home"></p>
                                    <a href="https://www.qnu.edu.vn/#" style="color:#fff">Bộ giáo dục và đào tạo</a>
                                </li>
                                <li>
                                    <p class="fa fa-home"></p>
                                    <a href="https://www.qnu.edu.vn/#" style="color:#fff">
                                        Tạp chí giáo dục
                                    </a>
                                </li>


                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.menu-items').on("click", function () {
                $(this).siblings().removeClass('active');
                $(this).addClass('active');
            });
        });
    </script>
</body>
</html>